[package]
name = "emoji"
version = "0.1.0"
authors = ["gb-2312 <gb-2312@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
